spring:
  application:
    name: quickfix

  datasource:
    url: jdbc:postgresql://localhost:5433/quickfix
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
